var githubUser = {
  "login": "vstetter",
  "id": 10333720,
  "avatar_url": "https://avatars.githubusercontent.com/u/10333720?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/vstetter",
  "html_url": "https://github.com/vstetter",
  "followers_url": "https://api.github.com/users/vstetter/followers",
  "following_url": "https://api.github.com/users/vstetter/following{/other_user}",
  "gists_url": "https://api.github.com/users/vstetter/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/vstetter/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/vstetter/subscriptions",
  "organizations_url": "https://api.github.com/users/vstetter/orgs",
  "repos_url": "https://api.github.com/users/vstetter/repos",
  "events_url": "https://api.github.com/users/vstetter/events{/privacy}",
  "received_events_url": "https://api.github.com/users/vstetter/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Veronika Stetter",
  "company": "",
  "blog": "",
  "location": "Charleston, SC",
  "email": "",
  "hireable": false,
  "bio": null,
  "public_repos": 15,
  "public_gists": 0,
  "followers": 1,
  "following": 0,
  "created_at": "2014-12-28T22:25:04Z",
  "updated_at": "2015-01-28T03:03:12Z"
};
